name: Sync to Organization Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Verificar que el secreto exista (sin mostrar el valor)
        run: |
          echo "Longitud del token:"
          echo "${{ secrets.TARGET_REPO_TOKEN }}" | wc -c

      - name: Configurar identidad de Git
        run: |
          git config --global user.email "salvaa4532@gmail.com"
          git config --global user.name "Franco Salvatore"

      - name: Agregar remote y hacer push mirror
        env:
          TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
        run: |
          git remote remove mirror || true
          git remote add mirror https://x-access-token:${TOKEN}@github.com/The-Martix/bioinfo-tools.git
          git push --mirror mirror
