name: Sync to Organization Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Configurar git user
        run: |
          git config --global user.email "salvaa4532@gmail.com"
          git config --global user.name "Franco Salvatore"

      - name: Remove existing mirror remote
        run: git remote remove mirror || true

      - name: Add mirror remote with token
        run: |
          git remote add mirror https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/The-Martix/bioinfo-tools.git
          
      - name: Show remote URL
        run: git remote -v

      - name: Push main branch to mirror
        run: |
          git push mirror main --force
