name: Sync to Organization Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
	
      - name: Check TOKEN secret
        run: echo "Token length: ${{ secrets.TARGET_REPO_TOKEN }} | wc -c"

      - name: Mirror push to organization repo
        run: |

          git config --global user.email "salvaa4532@gmail.com"
          git config --global user.name "SalvaFran"
          git remote add mirror https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/The-Martix/bioinfo-tools.git
          git push --mirror mirror
